/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.shreenidhi.sps;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import net.connectcode.Code128Auto;

/**
 *
 * @author USER
 */
public final class OperatorMainPage extends javax.swing.JFrame {

    /**
     * Creates new form OperatorMainPage
     */
     
    public OperatorMainPage() {
        initComponents();
        updatedetails();
        currentdate();  
         updateTransaction();
        Submit.setVisible(false);
          
       //transUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TodayDate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TodayTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCheckIn = new javax.swing.JButton();
        Barcode = new javax.swing.JTextField();
        VehicleNo = new javax.swing.JTextField();
        OwnerName = new javax.swing.JTextField();
        MobileNumber = new javax.swing.JTextField();
        ChekinTime = new javax.swing.JTextField();
        TransID = new javax.swing.JTextField();
        Clear1 = new javax.swing.JButton();
        PrintPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Barcode1 = new javax.swing.JTextField();
        DToday1 = new javax.swing.JLabel();
        OwnName = new javax.swing.JTextField();
        VNo = new javax.swing.JTextField();
        DTranID = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        SlotNumber = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Slots = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        DocType = new javax.swing.JComboBox<>();
        DocNumber = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        VehicleName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        VType = new javax.swing.JComboBox<>();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TID = new javax.swing.JTextField();
        GetDetails = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CustomerName = new javax.swing.JTextField();
        Sn = new javax.swing.JTextField();
        ATime = new javax.swing.JTextField();
        CheckOutTime = new javax.swing.JTextField();
        Fee = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Remark = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Paymentmode = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Duration = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Trn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operator Main Page");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Smart Parking System");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");

        TodayDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TodayDate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Time");

        TodayTime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TodayTime.setForeground(new java.awt.Color(255, 255, 255));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(35, 35, 35)
                        .addComponent(TodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(440, 440, 440)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TodayTime, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(TodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(TodayTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CheckIn Operation"));

        jLabel9.setText("Vehicle No               :-");

        jLabel10.setText("Owner Name            :-");

        jLabel11.setText("Moblie No                :-");

        jLabel12.setText("Check in Time          :-");

        jLabel13.setText("Transaction ID          :-");

        jLabel18.setText("BarCode");

        btnCheckIn.setText("   Confirm   ");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        Barcode.setEditable(false);
        Barcode.setBackground(new java.awt.Color(204, 204, 204));

        VehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleNoActionPerformed(evt);
            }
        });

        ChekinTime.setEditable(false);
        ChekinTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekinTimeActionPerformed(evt);
            }
        });

        TransID.setEditable(false);

        Clear1.setText("Clear");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });

        PrintPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel19.setText("Smart Parking System");

        jLabel22.setText("Name                 :-");

        jLabel23.setText("Vehicle No          :-");

        jLabel24.setText("Transaction Id     :-");

        Barcode1.setEditable(false);
        Barcode1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Barcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Barcode1ActionPerformed(evt);
            }
        });

        DToday1.setText(" ");

        OwnName.setEditable(false);
        OwnName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        OwnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnNameActionPerformed(evt);
            }
        });

        VNo.setEditable(false);
        VNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        DTranID.setEditable(false);
        DTranID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel29.setText("Slot No               :-");

        SlotNumber.setEditable(false);
        SlotNumber.setBorder(null);

        javax.swing.GroupLayout PrintPanelLayout = new javax.swing.GroupLayout(PrintPanel);
        PrintPanel.setLayout(PrintPanelLayout);
        PrintPanelLayout.setHorizontalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintPanelLayout.createSequentialGroup()
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel19))
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29))
                        .addGap(40, 40, 40)
                        .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OwnName)
                            .addComponent(VNo)
                            .addComponent(DTranID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(PrintPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SlotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PrintPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Barcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DToday1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PrintPanelLayout.setVerticalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(47, 47, 47)
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OwnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(VNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(SlotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(DTranID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(DToday1)
                .addGap(38, 38, 38))
        );

        jLabel25.setText("Available Slot           :-");

        jLabel26.setText("Document Type        :-");

        DocType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AADHAR CARD", "ELECTTION ID", "FORMER CARD", "GOVERNMENT CARD", "PASSPORT" }));
        DocType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocTypeActionPerformed(evt);
            }
        });

        jLabel27.setText("Document No           :-");

        jLabel28.setText("Vehicle Name           :-");

        jLabel20.setText("Vehicle Type            :-");

        VType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Wheeler", "4 Wheeler" }));

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addGap(153, 153, 153)
                .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print)
                .addContainerGap())
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCheckIn)
                .addGap(353, 353, 353))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(PrintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel20)
                            .addComponent(jLabel9))
                        .addGap(194, 194, 194)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DocNumber)
                            .addComponent(VehicleNo)
                            .addComponent(OwnerName)
                            .addComponent(MobileNumber)
                            .addComponent(ChekinTime)
                            .addComponent(TransID)
                            .addComponent(Slots, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DocType, 0, 200, Short.MAX_VALUE)
                            .addComponent(VehicleName)
                            .addComponent(VType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addComponent(Clear1)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(VehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(VType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(MobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(DocType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DocNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ChekinTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(TransID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(Slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Checkout Operation"));

        jLabel2.setText("Transaction Id :");

        TID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDActionPerformed(evt);
            }
        });

        GetDetails.setText("Get Details ");
        GetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDetailsActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Customer Name          : -");

        jLabel4.setText("Booked Slot No           :- ");

        jLabel5.setText("Booked Time              :-");

        jLabel6.setText("Checkout Time            :-");

        jLabel7.setText("Amount to pay            :-");

        CustomerName.setEditable(false);
        CustomerName.setBackground(new java.awt.Color(204, 204, 204));

        Sn.setEditable(false);
        Sn.setBackground(new java.awt.Color(204, 204, 204));
        Sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnActionPerformed(evt);
            }
        });

        ATime.setEditable(false);
        ATime.setBackground(new java.awt.Color(204, 204, 204));

        CheckOutTime.setEditable(false);
        CheckOutTime.setBackground(new java.awt.Color(204, 204, 204));

        Fee.setEditable(false);
        Fee.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel8.setText("Remarks                     :- ");

        jLabel14.setText("Payment Mode             :-");

        Paymentmode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit Card", "Debit Card", "Paytm", "Phone Pay", "Mobikwik", "Tez", "GooglePay" }));
        Paymentmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentmodeActionPerformed(evt);
            }
        });

        jLabel17.setText("   -:   Parking Duration:-   ");

        Duration.setEditable(false);
        Duration.setBackground(new java.awt.Color(204, 204, 204));

        jLabel21.setText("RS:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustomerName)
                            .addComponent(Sn)
                            .addComponent(ATime)
                            .addComponent(CheckOutTime, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Paymentmode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Remark, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit)
                .addGap(226, 226, 226))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ATime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Paymentmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Submit)
                .addGap(28, 28, 28))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", " ", " ", " ", " "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(GetDetails))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetDetails))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("   Transaction Details "));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Trn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TransId", "CustomerName", "SlotsNo", "Check In"
            }
        ));
        jScrollPane3.setViewportView(Trn);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public String DateDisplay="";
     public String TimeDisplay="";
    public void currentdate()
    {
        Calendar cal=new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        System.out.println(cal.getTime()); 
        
        //JOptionPane.showMessageDialog(null,cal.getTime());
        int sec=cal.get(Calendar.SECOND);
        int min=cal.get(Calendar.MINUTE);
        int mil=cal.get(Calendar.MILLISECOND);
        int hr=cal.get(Calendar.HOUR_OF_DAY);
       // PrintStream println = System.out.println("SECOND"+(String)sec);
        DateDisplay = day+""+(month+1);
        TimeDisplay = hr+""+min+""+sec;
        //TodayDate.setText(day+"/"+(month+1)+"/"+year+"TIME IS :"+hr+":"+min+":"+sec+":"+mil);
        TodayDate.setText(day+"/"+(month+1)+"/"+year);
        TodayTime.setText(hr+":"+min+":"+sec+":"+mil);
        //2019-04-03 22:44:15.000
        String ckin=year+"-"+(month+1)+"-"+day+" "+hr+":"+min+":"+sec+":"+mil;
            Date date=new Date();
            long time =date.getTime();
            Timestamp ts=new Timestamp(time); 
        ChekinTime.setText(""+ts);
        CheckOutTime.setText(""+ts);
       
        
    }
   
    public void PutcheckTime()
    {
         
 
    java.util.Date date = new java.util.Date();
    Timestamp timestamp1 = new Timestamp(date.getTime());
 
     // create a calendar and assign it the same time
    Calendar cal = Calendar.getInstance();
    cal.setTimeInMillis(timestamp1.getTime());
 
    // add a bunch of seconds to the calendar 
    cal.add(Calendar.SECOND, 98765);
 
    // create a  second time stamp
    Timestamp timestamp2 = new Timestamp(cal.getTime().getTime());
 
    // get time difference in seconds
    long milliseconds = timestamp2.getTime() - timestamp1.getTime();
    int seconds = (int) milliseconds / 1000;
 
    // calculate hours minutes and seconds
    int hours = seconds / 3600;
    int minutes = (seconds % 3600) / 60;
    seconds = (seconds % 3600) % 60;
 
 
    System.out.println("timestamp1: " + timestamp1);
     
     
    System.out.println("timestamp2: " + timestamp2);
 
    System.out.println("Difference: ");
    System.out.println(" Hours: " + hours);
    System.out.println(" Minutes: " + minutes);
    System.out.println(" Seconds: " + seconds); 
  }
    
    public void Chekout()
    {
    java.util.Date date = new java.util.Date();
    Timestamp timestamp1 = new Timestamp(date.getTime());
 
     // create a calendar and assign it the same time
    Calendar cal = Calendar.getInstance();
    cal.setTimeInMillis(timestamp1.getTime());
        CheckOutTime.setText(String(timestamp1));
    }
    public void updatedetails()
    {  
        try{
           ResultSet rs;
            String strqr="";
            Connection connection;  
            PreparedStatement stmt;
            RunMe rm=new RunMe();
         connection=DriverManager.getConnection(rm.StrUrl,rm.StrUid,rm.StrPwd);

             RunMe mc=new RunMe();
             
             PreparedStatement stmtq=connection.prepareStatement("select SlotNum from slotsdetails  where slotsdetails.SlotStatus='Available'");
            rs = stmtq.executeQuery();
            while (rs.next()){
                Slots.addItem(rs.getString(1));
            } 
            //Dimension size=Slots.getSize();
            if(Slots.getItemCount() == 0)
            
            {
              JOptionPane.showMessageDialog(this,"No Slots Availble ... Booking cannot Possible");  
              clearall();
              btnCheckIn.setVisible(false);
              print.setVisible(false);
              
            } 
            else {
            }
        }catch(SQLException upd)
        {
            System.out.println("Updatation Failed "+upd);
        }
      
    }
    public void clearall()
    {
        VehicleNo.setText("");
        VehicleName.setText("");
        MobileNumber.setText("");
        OwnerName.setText("");
        DocNumber.setText("");
        MobileNumber.setText("");
        DocNumber.setText("");
        ChekinTime.setText("");
        TransID.setText("");
        Barcode.setText("");
        Barcode1.setText("");
        OwnName.setText("");
        VNo.setText("");
        DTranID.setText("");
        Slots.removeAllItems();
        SlotNumber.setText("");
    }
    
     String chkin="";
    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
         
        if (VehicleNo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vehicle Number Not Found");
        }
        if (VehicleName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vehicle Name Not Found");
        }
        if (MobileNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " MobileNumber Not Found");
        }
        if (OwnerName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "OwnerName Not Found");
        }
        if (DocNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Document Number   Not Found");
        }
        
        Random rand = new Random();
        int nan=rand.nextInt(36000);  
        String t=TodayTime.getText();
        String d=TodayDate.getText();
        String code="TRA";
        String tt=code.concat(DateDisplay);
        String tot=tt.concat(TimeDisplay);
        tot=tot+nan;
        System.out.println("TRANSACTION ID:"+tot);
        TransID.setText(tot);
        System.out.println("DateDisplay :"+DateDisplay);
        System.out.println("\nTimeDisplay : "+TimeDisplay);
        
        
//        Code128Auto CD =new Code128Auto();
       // String barcode =CD.encode((String)tot);
         System.out.println("TRANSACTION ID for Barcode:"+tot);
         //Barcode.setText(barcode);
         //BarCode.setFont(new java.awt.Font("CCode128_S3_Trial",java.awt.Font.PLAIN,24));
        Barcode.setFont(new java.awt.Font("CCode128_S3_Trial",java.awt.Font.PLAIN,24)); 
       //  Barcode1.setText(barcode);
         //BarCode.setFont(new java.awt.Font("CCode128_S3_Trial",java.awt.Font.PLAIN,24));
        Barcode1.setFont(new java.awt.Font("CCode128_S3_Trial",java.awt.Font.PLAIN,24));
        
        OwnName.setText("");
        VNo.setText("");
        DTranID.setText(tot); 
         ResultSet rs;
            String strqr="";
            Connection connection;  
            PreparedStatement stmt;
            ResultSet rsbook = null;
            RunMe rm=new RunMe();
            ResultSet rsmem;
            boolean chadd=false;
              try
        {
        
            //String strqr="";
          // Connection connection;          
           
              RunMe mc=new RunMe();
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd); 
            String sql = "insert into transaction (TransId,VehicleNo,Date,Time,IdCard,IdNumber,VType,SlotNo,VehicleName,CustName) values(?,?,?,?,?,?,?,?,?,?) ";
            PreparedStatement pst=connection.prepareStatement(sql);
            pst.setString(1,TransID.getText());
            pst.setString(2,VehicleNo.getText());
            pst.setString(3,TodayDate.getText());
            pst.setString(4,TodayTime.getText());
            pst.setString(5, (String) DocType.getSelectedItem());
            pst.setString(6,DocNumber.getText());
            pst.setString(7,(String) VType.getSelectedItem());
            pst.setString(8,(String) Slots.getSelectedItem());
            pst.setString(9,VehicleName.getText());
            pst.setString(10,OwnerName.getText());
            //pst.setString(11,TodayTime.getText());
            //pst.setString(11,ChekinTime.getText());
             pst.executeUpdate();
            try{
              String sqlc = "insert into customer (CustomerName,VehicleNumber,Phone,IDCard,IDNumber,Regidate) values(?,?,?,?,?,?) ";
            PreparedStatement pstc=connection.prepareStatement(sqlc);
            pstc.setString(1,OwnerName.getText());
            pstc.setString(2,VehicleNo.getText());
            pstc.setString(3,MobileNumber.getText());
            pstc.setString(4, (java.lang.String) DocType.getSelectedItem());
            pstc.setString(5,DocNumber.getText());
            pstc.setString(6,TodayDate.getText()); 
             pstc.executeUpdate();
                
            }catch(SQLException custUpdateError)
            {
                System.out.println("Customer Insertion Failed");
                JOptionPane.showMessageDialog(this,"Customer Updation Failed");
            }
            //VEHICLE UPDATION
            try{
              String sqlc1 = "insert into vehicle (VehicleNumber,VehicleOwner,VehicleType,IDNumber,Regidate) values(?,?,?,?,?) ";
            PreparedStatement pstc1=connection.prepareStatement(sqlc1);
            pstc1.setString(1,VehicleNo.getText());
            pstc1.setString(2,OwnerName.getText());
            pstc1.setString(3, (java.lang.String) VType.getSelectedItem());
            pstc1.setString(4, DocNumber.getText());
            pstc1.setString(5,TodayDate.getText()); 
             pstc1.executeUpdate();
                
            }catch(SQLException  VUE)
            {
                System.out.println("Vehicle Insertion Failed :\n"+VUE);
                JOptionPane.showMessageDialog(this,"Vehicle Updation Failed\n"+VUE);
            }
             
             String tc;
             tc=TransID.getText();
            String sql1="update  transaction  set  CI  = sysdate() where TransId='"+tc+"'";
            PreparedStatement pst1=connection.prepareStatement(sql1);
            pst1.execute();
            
            String sql2="update  transaction  set  UpdatedTime  = sysdate() where TransId='"+tc+"'";
            PreparedStatement pst2=connection.prepareStatement(sql2);
            pst2.execute();
            String u="Occupied";
            String sdf=(String)Slots.getSelectedItem();
            String sql3="update  slotsdetails  set  SlotStatus  = '"+u+"' where SlotNum='"+sdf+"'";
            PreparedStatement pst3=connection.prepareStatement(sql3);
            pst3.execute();
            String fs="Pending";
           String sql4="update  transaction  set  FeeStatus  = '"+fs+"' where TransId='"+tc+"'";
            PreparedStatement pst4=connection.prepareStatement(sql4);
            pst4.execute();
            
            OwnName.setText(OwnerName.getText());
            SlotNumber.setText((java.lang.String) Slots.getSelectedItem());
            VNo.setText(VehicleNo.getText());
            Slots.removeAllItems();
            updatedetails();
            currentdate();  updateTransaction();
             
            btnCheckIn.setVisible(false);
             Slots.removeAllItems();
        }
        catch (SQLException e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Un Successfull .\n"+e);
        }
              
               
       
    }//GEN-LAST:event_btnCheckInActionPerformed
  
      
 
    private void VehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleNoActionPerformed

    private void ChekinTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekinTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChekinTimeActionPerformed

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
        // TODO add your handling code here:
        VehicleNo.setText("");
        CustomerName.setText("");
        MobileNumber.setText("");
        CustomerName.setText("");
        VehicleName.setText("");
        DocNumber.setText("");
        currentdate();
    }//GEN-LAST:event_Clear1ActionPerformed

    private void Barcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Barcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Barcode1ActionPerformed

    private void OwnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnNameActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
            updatedetails();
           currentdate();
      PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("RECEIPT");
        job.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.75, 1.0);
            PrintPanel.paint(g2);
            return Printable.PAGE_EXISTS;
           });

        Boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
                System.out.println(ex);
            }
        }
        btnCheckIn.setVisible(true);
        clearall();
        PutcheckTime();
        currentdate(); 
        updatedetails();
    }//GEN-LAST:event_printActionPerformed

    private void GetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDetailsActionPerformed
        // TODO add your handling code here:
            String StrQr="";
         if (TID.getText().trim().length()>0 )
            {
                StrQr=StrQr + " and TransId like '%" + TID.getText().trim() + "%' ";
                if (StrQr.length()==0)
                {
               JOptionPane.showMessageDialog(null,"Enter search critaria.");
                }
            }
         
        try{
            
             RunMe mc=new RunMe();
            
            Connection connection;          
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            ResultSet rs;

        
             PreparedStatement stmt=connection.prepareStatement("select TransId,SlotNo, CustName, CI  from transaction where TransId='"+TID.getText()+"'");
            rs = stmt.executeQuery();
            // Removing Previous Data
            while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            } 
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next())
            {  
            CustomerName.setText(rs.getString("CustName"));
            Sn.setText(rs.getString("SlotNO"));
            ATime.setText(rs.getString("CI")); 
            }
             
            connection.close();
            
            String ArTime;
            String DeTime;
            ArTime=ATime.getText();
            DeTime=CheckOutTime.getText();
             Timestamp t1=Timestamp.valueOf(ArTime);
             Timestamp t2=Timestamp.valueOf(DeTime);
             long millisecond =t2.getTime() - t1.getTime();
             int second = (int) millisecond / 1000;
             int hour=second/36000;
             int mini=(second % 36000)/60;
             second=(second%3600)%60; 
             String Display;
             Display=""+hour+" Hours "+mini+" Minutes and "+second+" Seconds";
             Duration.setText(Display);
             int sum=0;
             if(mini<=30)
                 sum=50;
             if(mini>=31 && mini<=60)
                 sum=100;
             if(mini>=61 && mini <=120)
                 sum=150;
             if(mini >=121 && mini <=160)
                 sum=200;
             if(mini>161)
                 sum=500;
             Fee.setText(""+sum);
             Slots.removeAllItems();
            
        }catch(HeadlessException | SQLException gd)
        {
            System.out.println("Error in GetDetails  "+gd);
        }     
        
    }//GEN-LAST:event_GetDetailsActionPerformed
public void updateTransaction()
{
    try {
            RunMe mc=new RunMe();
            
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            ResultSet rs;
            
            
            
            
            PreparedStatement stmt=connection.prepareStatement("SELECT TransId,CustName,SlotNo,FeeStatus  FROM transaction ORDER BY UpdatedTime DESC ");
            rs = stmt.executeQuery();   
        Trn.getColumnModel().getColumn(0).setHeaderValue("TransId");
        Trn.getColumnModel().getColumn(1).setHeaderValue("Customer Name");
        Trn.getColumnModel().getColumn(2).setHeaderValue("SlotName");
        Trn.getColumnModel().getColumn(3).setHeaderValue("Payement Status");
       //Trn.getColumnModel().getColumn(4).setHeaderValue("CheckOut");
        //Trn.getColumnModel().getColumn(5).setHeaderValue("lastUpdated");
         
        Trn.getTableHeader().resizeAndRepaint(); 
            while (Trn.getRowCount() > 0) {
                ((DefaultTableModel) Trn.getModel()).removeRow(0);
            } 
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    row[i - 1] = rs.getObject(i); // 1
                }
                ((DefaultTableModel) Trn.getModel()).insertRow(rs.getRow() - 1,row);
            }
            
        } catch (SQLException e) {
            System.err.println(e);
            //System.exit(1);
        }
}
    public void departclear()
{
            TID.setText("");
            CustomerName.setText("");
            Sn.setText("");
            ATime.setText("");
            Duration.setText("");
            Fee.setText("");
            Remark.setText("");
}
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try
        {
            //get database connection details
            RunMe mc=new RunMe();
            String tc;
            tc=TID.getText();
             //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String sql1="update  transaction  set  CO  = sysdate() where TransId='"+tc+"'";
            PreparedStatement pst1=connection.prepareStatement(sql1);
            pst1.execute();
            //Fee Payment
            String sql11="update  transaction  set  Amount  = '"+Fee.getText()+"' where TransId='"+tc+"'";
            PreparedStatement pst11=connection.prepareStatement(sql11);
            pst11.execute();
            //Fee Status
            String sql12="update  transaction  set  FeeStatus  = '"+"Paid"+"' where TransId='"+tc+"'";
            PreparedStatement pst12=connection.prepareStatement(sql12);
            pst12.execute();
            //
             String sql2="update  transaction  set  UpdatedTime  = sysdate() where TransId='"+tc+"'";
            PreparedStatement pst2=connection.prepareStatement(sql2);
            pst2.execute();
            String sdf=Sn.getText();
            java.lang.String u="Available";
            String sql3="update  slotsdetails  set  SlotStatus  = '"+u+"' where SlotNum='"+sdf+"'";
            PreparedStatement pst3=connection.prepareStatement(sql3);
            pst3.execute(); 
        currentdate();
        departclear();
         updateTransaction();
        }
        catch(SQLException Ex)
        {
            System.out.println("Checkout Problem"+Ex);
        }
         Submit.setVisible(false); 
         updatedetails();
         // transUpdate();
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        OperatorLogin op=new OperatorLogin();
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DocTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocTypeActionPerformed

    private void PaymentmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentmodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentmodeActionPerformed

    private void SnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:currentdate();
        Submit.setVisible(true);
        currentdate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        departclear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OperatorMainPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATime;
    private javax.swing.JTextField Barcode;
    private javax.swing.JTextField Barcode1;
    private javax.swing.JTextField CheckOutTime;
    private javax.swing.JTextField ChekinTime;
    private javax.swing.JButton Clear1;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JLabel DToday1;
    private javax.swing.JTextField DTranID;
    private javax.swing.JTextField DocNumber;
    private javax.swing.JComboBox<String> DocType;
    private javax.swing.JTextField Duration;
    private javax.swing.JTextField Fee;
    private javax.swing.JButton GetDetails;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JTextField OwnName;
    private javax.swing.JTextField OwnerName;
    private javax.swing.JComboBox<String> Paymentmode;
    private javax.swing.JPanel PrintPanel;
    private javax.swing.JTextField Remark;
    private javax.swing.JTextField SlotNumber;
    private javax.swing.JComboBox<String> Slots;
    private javax.swing.JTextField Sn;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TID;
    private javax.swing.JLabel TodayDate;
    private javax.swing.JLabel TodayTime;
    private javax.swing.JTextField TransID;
    private javax.swing.JTable Trn;
    private javax.swing.JTextField VNo;
    private javax.swing.JComboBox<String> VType;
    private javax.swing.JTextField VehicleName;
    private javax.swing.JTextField VehicleNo;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables

    private String String(Timestamp timestamp1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void ChekinTime() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
